#!/bin/bash
# DNS Setup Instructions for rei.openclapp.com

echo "=== DNS Configuration Required ==="
echo ""
echo "Domain: rei.openclapp.com"
echo "Target IP: 16.59.79.163"
echo ""
echo "Action Required:"
echo "1. Log in to GoDaddy DNS management for openclapp.com"
echo "2. Add the following A record:"
echo ""
echo "   Type: A"
echo "   Name: rei"
echo "   Value: 16.59.79.163"
echo "   TTL: 600 (or default)"
echo ""
echo "3. Wait for DNS propagation (usually 5-30 minutes)"
echo ""
echo "4. Verify with: dig rei.openclapp.com"
echo ""
echo "5. Once DNS resolves, run the SSL certificate setup:"
echo "   sudo certbot --nginx -d rei.openclapp.com"
echo ""
